### ISSUE TITLE
How do you get the worksheetId and sheetId?

### ISSUE THREAD

**Issue by hokster7** [pyro2927/GoogleDocsBackend#4]
Not clear at all!

**Comment by pyro2927** [comment]
After you pushing a document, you'll get a share-able URL:

![](https://dl.dropboxusercontent.com/s/tfevdoabopy2k0s/2015-05-11%20at%208.23%20PM%202x.png?dl=0)

It'll be in the format `https://docs.google.com/spreadsheets/d/WORKSHEET_ID_HERE/pubhtml`.  Take that and put it into the url `https://spreadsheets.google.com/feeds/worksheets/WORKSHEET_ID/public/basic?alt=json`, load it up, and view the JSON.  The sheets and their IDs will be in `['feed']['entry'][N]['id']['$t']` (shown in a the README [here](https://github.com/pyro2927/GoogleDocsBackend/raw/master/img/worksheet_json.png)).
